# Generated by Django 5.2.4 on 2025-11-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_dummy_field',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
