# Generated by Django 5.2.4 on 2025-11-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_test_dummy_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shipping_address1',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_address2',
        ),
    ]
