# Generated by Django 5.2.4 on 2025-11-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_shipping_address1_user_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='shipping_address1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test_dummy_field',
        ),
        migrations.AddField(
            model_name='user',
            name='shipping_address2',
            field=models.TextField(blank=True),
        ),
    ]
