# Generated by Django 5.2.4 on 2025-12-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='house_no',
            new_name='streetorhouse_no',
        ),
    ]
