# Generated by Django 5.2.4 on 2025-12-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_house_no_shippingaddress_streetorhouse_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='contact',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='streetorhouse_no',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='contact_person',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='location_description',
            field=models.TextField(blank=True, default='Location', null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='province',
            field=models.CharField(max_length=50),
        ),
    ]
