# Generated by Django 5.2.4 on 2025-12-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_contact_shippingaddress_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
