# Generated by Django 5.2.4 on 2025-12-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_added_at_cart_created_at_remove_cart_cart_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
