# Generated by Django 5.2.4 on 2025-11-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_remove_productvariant_stock_delete_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('average_cost', models.FloatField(default=0)),
                ('productvariant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('cost_per_unit', models.FloatField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('productvariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktransactions', to='products.productvariant')),
            ],
        ),
    ]
