# Generated by Django 5.2.4 on 2025-11-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0011_remove_productvariant_stock_delete_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productvariant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventorystocks', to='products.productvariant'),
        ),
    ]
