# Generated by Django 5.2.4 on 2025-11-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_total_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock',
            new_name='quantity',
        ),
    ]
