# Generated by Django 5.2.4 on 2025-11-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_stock_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='average_cost',
            new_name='cost_per_unit',
        ),
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='cost_per_unit',
            new_name='transaction_cost',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='stock',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
