# Generated by Django 5.1.3 on 2025-12-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_options_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_orderitem_amount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
