# Generated by Django 5.2.4 on 2025-11-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_name_category_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='front_image',
        ),
        migrations.DeleteModel(
            name='SEO',
        ),
    ]
