# Generated by Django 5.2.4 on 2025-11-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_rename_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(default='logo', upload_to='images/brands/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_picture',
            field=models.ImageField(default='picture', upload_to='images/brands/'),
        ),
    ]
