# Generated by Django 5.2.4 on 2025-11-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_brand_brand_logo_alter_brand_brand_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productvariants', to='products.product'),
        ),
    ]
