# Generated by Django 5.2.4 on 2025-11-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariant_low_stock_threshold_stockhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='variant',
            new_name='productvariant',
        ),
    ]
