# Generated by Django 5.2.4 on 2025-11-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_variant_stockhistory_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
