# Generated by Django 5.2.4 on 2025-11-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productvariant_stock_delete_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/variants/'),
        ),
    ]
