# Generated by Django 5.2.4 on 2025-12-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_brand_is_active_category_is_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
