# Generated by Django 5.2.4 on 2025-12-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_brand_is_active_remove_category_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
    ]
